import { defineConfig } from "tsup";

export default defineConfig({
	entry: ["src/index.ts"],
	outDir: "dist",
	sourcemap: true,
	clean: true,
	format: ["esm"],
	platform: "node",
	target: "node18",
	external: [
		// Node.js built-ins (including node: prefixed versions)
		"form-data",
		"combined-stream",
		"axios",
		"util",
		"stream",
		"http",
		"https",
		"events",
		"crypto",
		"buffer",
		"url",
		"zlib",
		"querystring",
		"os",
		"fs",
		"path",
		"assert",
		"child_process",
		"cluster",
		"dgram",
		"dns",
		"domain",
		"fs/promises",
		"module",
		"net",
		"perf_hooks",
		"process",
		"punycode",
		"readline",
		"repl",
		"string_decoder",
		"sys",
		"timers",
		"tls",
		"tty",
		"v8",
		"vm",
		"worker_threads",
		// Node.js built-ins with node: prefix
		"node:os",
		"node:fs",
		"node:path",
		"node:util",
		"node:stream",
		"node:http",
		"node:https",
		"node:events",
		"node:crypto",
		"node:buffer",
		"node:url",
		"node:zlib",
		"node:querystring",
		"node:assert",
		"node:child_process",
		"node:cluster",
		"node:dgram",
		"node:dns",
		"node:domain",
		"node:fs/promises",
		"node:module",
		"node:net",
		"node:perf_hooks",
		"node:process",
		"node:punycode",
		"node:readline",
		"node:repl",
		"node:string_decoder",
		"node:sys",
		"node:timers",
		"node:tls",
		"node:tty",
		"node:v8",
		"node:vm",
		"node:worker_threads",
		// Third-party modules with native dependencies
		"@reflink/reflink",
		"@node-llama-cpp",
		"agentkeepalive",
		"csv-writer",
		"csv-parse/sync",
		"dotenv",
		"advanced-sdk-ts",
		"jsonwebtoken",
		"whatwg-url",
		"@realityspiral/sentry",
		// Native modules that should not be bundled
		"@anush008/tokenizers",
		"better-sqlite3",
		"ws",
		"ethers",
		"viem",
		// Logging libraries that use dynamic requires
		"pino",
		"pino-pretty",
		"pino/file",
		"pino/stdSerializers",
		// Other problematic dependencies
		"fsevents",
		"chokidar",
		"glob",
		"minimatch",
		"brace-expansion",
		"balanced-match",
		"concat-map",
		"path-is-absolute",
		"is-extglob",
		"is-glob",
		"normalize-path",
		"picomatch",
		"micromatch",
		"braces",
		"fill-range",
		"to-regex-range",
		"is-number",
		"kind-of",
		"is-buffer",
		"is-extendable",
		"assign-symbols",
		"extend-shallow",
		"is-plain-object",
		"shallow-clone",
		"split-string",
		"repeat-element",
		"repeat-string",
		"to-regex",
		"define-property",
		"is-descriptor",
		"is-accessor-descriptor",
		"is-data-descriptor",
		// Core dependencies that should be externalized
		"@elizaos/core",
		"zod",
		"@realityspiral/plugin-instrumentation",
	],
	noExternal: [],
});
