services:
  realityspiral:
    restart: always
    image: ghcr.io/sifchain/realityspiral:staging
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - CHARACTERS=${CHARACTERS}
      - SERVER_PORT=${SERVER_PORT}
      - UI_PORT=${UI_PORT}
      - UI_ALLOWED_HOSTS=${UI_ALLOWED_HOSTS}
      - UI_SERVER_URL=${UI_SERVER_URL}
      - REMOTE_CHARACTER_URLS=${REMOTE_CHARACTER_URLS}
      - USE_CHARACTER_STORAGE=${USE_CHARACTER_STORAGE}
      - DEFAULT_LOG_LEVEL=${DEFAULT_LOG_LEVEL}
      - LOG_JSON_FORMAT=${LOG_JSON_FORMAT}
      - INSTRUMENTATION_ENABLED=${INSTRUMENTATION_ENABLED}
      - TWITTER_CLIENT_DISABLED=${TWITTER_CLIENT_DISABLED}
      - TWITTER_DRY_RUN=${TWITTER_DRY_RUN}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - POST_INTERVAL_MIN=${POST_INTERVAL_MIN}
      - POST_INTERVAL_MAX=${POST_INTERVAL_MAX}
      - POST_IMMEDIATELY=${POST_IMMEDIATELY}
      - ACTION_INTERVAL=${ACTION_INTERVAL}
      - ENABLE_ACTION_PROCESSING=${ENABLE_ACTION_PROCESSING}
      - MAX_ACTIONS_PROCESSING=${MAX_ACTIONS_PROCESSING}
      - ACTION_TIMELINE_TYPE=${ACTION_TIMELINE_TYPE}
      - TWITTER_APPROVAL_DISCORD_CHANNEL_ID=${TWITTER_APPROVAL_DISCORD_CHANNEL_ID}
      - TWITTER_APPROVAL_DISCORD_BOT_TOKEN=${TWITTER_APPROVAL_DISCORD_BOT_TOKEN}
      - TWITTER_APPROVAL_ENABLED=${TWITTER_APPROVAL_ENABLED}
      - TWITTER_APPROVAL_CHECK_INTERVAL=${TWITTER_APPROVAL_CHECK_INTERVAL}
      - TELEGRAM_CLIENT_DISABLED=${TELEGRAM_CLIENT_DISABLED}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - EXPRESS_MAX_PAYLOAD=${EXPRESS_MAX_PAYLOAD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - SMALL_OPENAI_MODEL=${SMALL_OPENAI_MODEL}
      - MEDIUM_OPENAI_MODEL=${MEDIUM_OPENAI_MODEL}
      - LARGE_OPENAI_MODEL=${LARGE_OPENAI_MODEL}
      - EMBEDDING_OPENAI_MODEL=${EMBEDDING_OPENAI_MODEL}
      - IMAGE_OPENAI_MODEL=${IMAGE_OPENAI_MODEL}
      - USE_OPENAI_EMBEDDING=${USE_OPENAI_EMBEDDING}
      - COINBASE_CLIENT_DISABLED=${COINBASE_CLIENT_DISABLED}
      - COINBASE_COMMERCE_KEY=${COINBASE_COMMERCE_KEY}
      - COINBASE_API_KEY=${COINBASE_API_KEY}
      - COINBASE_PRIVATE_KEY=${COINBASE_PRIVATE_KEY}
      - COINBASE_GENERATED_WALLET_ID=${COINBASE_GENERATED_WALLET_ID}
      - COINBASE_GENERATED_WALLET_HEX_SEED=${COINBASE_GENERATED_WALLET_HEX_SEED}
      - COINBASE_TRADING_AMOUNT=${COINBASE_TRADING_AMOUNT}
      - COINBASE_SHORT_TERM_TRADING_WALLET_SEED=${COINBASE_SHORT_TERM_TRADING_WALLET_SEED}
      - COINBASE_SHORT_TERM_TRADING_WALLET_ID=${COINBASE_SHORT_TERM_TRADING_WALLET_ID}
      - COINBASE_LONG_TERM_TRADING_WALLET_SEED=${COINBASE_LONG_TERM_TRADING_WALLET_SEED}
      - COINBASE_LONG_TERM_TRADING_WALLET_ID=${COINBASE_LONG_TERM_TRADING_WALLET_ID}
      - COINBASE_DRY_POWDER_WALLET_SEED=${COINBASE_DRY_POWDER_WALLET_SEED}
      - COINBASE_DRY_POWDER_WALLET_ID=${COINBASE_DRY_POWDER_WALLET_ID}
      - COINBASE_OPERATIONAL_CAPITAL_WALLET_SEED=${COINBASE_OPERATIONAL_CAPITAL_WALLET_SEED}
      - COINBASE_OPERATIONAL_CAPITAL_WALLET_ID=${COINBASE_OPERATIONAL_CAPITAL_WALLET_ID}
      - COINBASE_MASS_PAYMENTS_PAYMENT_ENABLED=${COINBASE_MASS_PAYMENTS_PAYMENT_ENABLED}
      - COINBASE_TRADE_PLUGIN_ENABLED=${COINBASE_TRADE_PLUGIN_ENABLED}
      - COINBASE_TOKEN_CONTRACT_PLUGIN_ENABLED=${COINBASE_TOKEN_CONTRACT_PLUGIN_ENABLED}
      - COINBASE_ADVANCED_TRADE_PLUGIN_ENABLED=${COINBASE_ADVANCED_TRADE_PLUGIN_ENABLED}
      - COINBASE_WEBHOOK_PORT=${COINBASE_WEBHOOK_PORT}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - WALLET_PUBLIC_KEY=${WALLET_PUBLIC_KEY}
      - ZERO_EX_API_KEY=${ZERO_EX_API_KEY}
      - BASE_RPC_URL=${BASE_RPC_URL}
      - ALCHEMY_HTTP_TRANSPORT_URL=${ALCHEMY_HTTP_TRANSPORT_URL}
      - GITHUB_CLIENT_DISABLED=${GITHUB_CLIENT_DISABLED}
      - GITHUB_PLUGIN_ENABLED=${GITHUB_PLUGIN_ENABLED}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - GITHUB_USER_CHECK_INTERVAL_MS=${GITHUB_USER_CHECK_INTERVAL_MS}
      - GITHUB_INFO_DISCOVERY_INTERVAL_MS=${GITHUB_INFO_DISCOVERY_INTERVAL_MS}
      - GITHUB_OODA_INTERVAL_MS=${GITHUB_OODA_INTERVAL_MS}
      - GITHUB_ISSUES_LIMIT=${GITHUB_ISSUES_LIMIT}
      - GITHUB_PULL_REQUESTS_LIMIT=${GITHUB_PULL_REQUESTS_LIMIT}
      - POSTGRES_URL=${POSTGRES_URL}
