services:
  realityspiral:
    restart: always
    image: ghcr.io/sifchain/realityspiral:staging
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - CHARACTERS=${CHARACTERS}
      - SERVER_PORT=${SERVER_PORT}
      - UI_PORT=${UI_PORT}
      - UI_SERVER_URL=${UI_SERVER_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ROFL_PLUGIN_ENABLED=${ROFL_PLUGIN_ENABLED}
      - ACCUMULATED_FINANCE_ENABLED=${ACCUMULATED_FINANCE_ENABLED}
      - BITPROTOCOL_ENABLED=${BITPROTOCOL_ENABLED}
      - NEBY_ENABLED=${NEBY_ENABLED}
      - THORN_ENABLED=${THORN_ENABLED}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock